groups:
  - name: url-shortener-alerts
    rules:
      - alert: HighErrorRate
        expr: rate(http_requests_total{status=~"5.."}[5m]) > 0.05
        for: 10m
        labels:
          severity: "critical"
        annotations:
          summary: "High error rate"
          description: "The error rate is above 5% for the last 10 minutes."

      - alert: SlowResponseTime
        expr: histogram_quantile(0.95, rate(http_request_duration_seconds_bucket[5m])) > 0.5
        for: 5m
        labels:
          severity: "warning"
        annotations:
          summary: "Slow response time"
          description: "95th percentile of response time is greater than 0.5 seconds for the last 5 minutes."