version: '3.7'

services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"

  kibana:
    image: docker.elastic.co/kibana/kibana:7.10.1
    ports:
      - "5601:5601"

  logstash:
    image: docker.elastic.co/logstash/logstash:7.10.1
    ports:
      - "5044:5044"
      - "9600:9600"
    volumes:
      - ./Monitoring/logstash.conf:/usr/share/logstash/pipeline # Монтируем конфигурационный файл Logstash

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./Monitoring/prometheus.yml:/etc/prometheus # Монтируем конфигурационный файл Prometheus

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
