
- name: Configure Prometheus and Grafana
  hosts: all
  become: true

  tasks:
  - name: Install Prometheus
    apt:
      name: prometheus
      state: present

  - name: Install Grafana
    apt:
      name: grafana
      state: present

  - name: Start Prometheus service
    systemd:
      name: prometheus
      state: started
      enabled: yes

  - name: Copy Prometheus configuration file
    copy:
        src: /home/ubuntu/url-shortener/prometheus/prometheus.yml   # Path to your Prometheus configuration file
        dest: /etc/prometheus/prometheus.yml
        owner: prometheus
        group: prometheus
        mode: '0644'

  - name: Copy Prometheus configuration file
    copy:
        src: /home/ubuntu/url-shortener/rules.yml   # Path to your Prometheus configuration file
        dest: /etc/prometheus/rules.yml
        owner: prometheus
        group: prometheus
        mode: '0644'

  - name: Start Grafana service
    systemd:
      name: grafana-server
      state: started
      enabled: yes

