---
- name: Configure web server
  hosts: web_servers
  become: true

  tasks:
    - name: Update and upgrade apt packages
      apt:
        update_cache: yes
        upgrade: yes

    - name: Install Prometheus
      shell: |
        wget https://github.com/prometheus/prometheus/releases/download/v2.36.2/prometheus-2.36.2.linux-amd64.tar.gz
        tar xvfz prometheus-2.36.2.linux-amd64.tar.gz
        mv prometheus-2.36.2.linux-amd64/prometheus /usr/local/bin/
        mv prometheus-2.36.2.linux-amd64/promtool /usr/local/bin/
        useradd -M -r -s /bin/false prometheus
        mkdir /etc/prometheus
        mkdir /var/lib/prometheus
        chown prometheus:prometheus /var/lib/prometheus
        mv prometheus-2.36.2.linux-amd64/prometheus.yml /etc/prometheus/
        chown prometheus:prometheus /etc/prometheus/prometheus.yml

    - name: Create Prometheus systemd service
      copy:
        content: |
          [Unit]
          Description=Prometheus
          Wants=network-online.target
          After=network-online.target

          [Service]
          User=prometheus
          Group=prometheus
          Type=simple
          ExecStart=/usr/local/bin/prometheus \
            --config.file=/etc/prometheus/prometheus.yml \
            --storage.tsdb.path=/var/lib/prometheus/ \
            --web.console.templates=/usr/local/bin/prometheus/consoles \
            --web.console.libraries=/usr/local/bin/prometheus/console_libraries

          [Install]
          WantedBy=multi-user.target
        dest: /etc/systemd/system/prometheus.service
        owner: root
        group: root
        mode: 0644

    - name: Reload systemd and start Prometheus service
      systemd:
        daemon_reload: yes
        name: prometheus
        state: started
        enabled: yes

    - name: Install Grafana
      shell: |
        wget https://dl.grafana.com/oss/release/grafana_8.4.4_amd64.deb
        dpkg -i grafana_8.4.4_amd64.deb

    - name: Start and enable Grafana service
      systemd:
        name: grafana-server
        state: started
        enabled: yes
