name: Deploy and Configure EC2

on:
  push:
    branches:
      - main

jobs:
  terraform:
    name: Terraform Apply
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.1.5

      - name: Terraform Init
        working-directory: ./terraform
        run: terraform init

      - name: Terraform Apply
        working-directory: ./terraform
        run: terraform apply -auto-approve
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Save instance IP
        id: save_ip
        run: echo "::set-output name=instance_ip::$(terraform output -raw instance_ip)"
        working-directory: ./terraform

  ansible:
    name: Ansible Configure
    runs-on: ubuntu-latest
    needs: terraform

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Ansible
        run: sudo apt-get update && sudo apt-get install -y ansible

      - name: Configure inventory
        run: echo "[web_servers]\n${{ needs.terraform.outputs.instance_ip }}" > ansible/inventory

      - name: Run Ansible Playbook
        run: ansible-playbook -i ansible/inventory -u ubuntu --private-key ${{ secrets.AWS_PRIVATE_KEY }} ansible/playbook.yml
