# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21.1'

    # - name: Build
    #   run: go build -v ./cmd/url-shortener
    # - name: Install dependencies
    #   run: go get .
    - name: Run site
      run: go run ./cmd/url-shortener
    - name: Test General
      run: go test -v ./tests
    - name : Test redirect
      run: go test -v ./internal/http-server/handlers/redirect
    - name : Test redirect
      run: go test -v ./internal/http-server/handlers/save
